(defproject sokoban2 "0.1.0-SNAPSHOT"
  :description "An attempt to make online sokoban game with autogenerated levels"
  :url "http://github.com/mzdravkov/sokoban"
  :license {:name "Eclipse Public License"
            :url "http://www.eclipse.org/legal/epl-v10.html"}
  :dependencies [[org.clojure/clojure "1.5.1"]
                 [org.clojure/tools.trace "0.7.6"]
                 [org.clojure/clojurescript "0.0-2173"
                  :exclusions [org.apache.ant/ant]]
                 [compojure "1.1.6"]
                 [clj-time "0.6.0"]
                 [hiccup "1.0.4"]]
  :plugins [[lein-ring "0.8.10"]
            [lein-cljsbuild "1.0.2"]]
  :cljsbuild {:builds [{:source-paths ["src-cljs"]
                        :compiler {:output-to "resources/public/js/main.js"
                                   :optimizations :whitespace
                                   :pretty-print true}}]}
  :ring {:handler sokoban2.handler/app})
