(defproject sokoban2 "0.1.0-SNAPSHOT"
  :description "An attempt to make online sokoban game with autogenerated levels"
  :url "http://github.com/mzdravkov/sokoban"
  :license {:name "Eclipse Public License"
            :url "http://www.eclipse.org/legal/epl-v10.html"}
  :dependencies [[org.clojure/clojure "1.5.1"]
                 [lein-reload "1.0.0"]
                 [org.clojure/data.priority-map "0.0.2"]
                 [net.mikera/core.matrix "0.19.0"]])
